name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dependencies
      run: |
        sudo apt-get install cppcheck
        sudo apt-get install valgrind

    - name: compile
      run: initial_compiling

    - name: cppcheck
      run: cppcheck

    - name: unity
      run: unity
    
    - name: valgrind
      run: valgrind

    - name: sanitizer
      run: sanitizer
